_extends: .github
repository:
  name: babel-plugin-universal-dotenv
  description: create-react-app's dotenv resolution as a babel plugin
  homepage: https://saiichihashimoto.github.io/babel-plugin-universal-dotenv/
  topics: babel, babel-plugin, create-react-app, dotenv, universal-dotenv
branches:
  - name: master
    protection:
      required_status_checks:
        contexts: ['Semantic Pull Request', 'WIP', 'continuous-integration/travis-ci', 'coverage/coveralls']
