language: node_js
node_js:
  - 11
notifications:
  email:
    - saiichihashimoto@gmail.com
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
after_success:
  - cat ./coverage/lcov.info | npx coveralls --verbose
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npx semantic-release
