language: node_js
cache: npm
node_js:
  - 11
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - saiichihashimoto@gmail.com
    on_success: never
    on_failure: always
script:
  - npm test && npx stryker run
after_success:
  - cat ./coverage/lcov.info | npx coveralls
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npx semantic-release
